### ISSUE TITLE
感谢作者分享读书笔记

### ISSUE THREAD

**Issue by Cxk4ng** [uniblackfire/AndroidReverseEngineeringScript#1]
我想尝试正则替换所有的工程中所有返回，crack 文件夹可以分享给我吗 :+1:

**Comment by uniblackfire** [comment]
不好意思现在才看到。
请问你邮箱多少呢

**Comment by uniblackfire** [comment]
我的邮箱是uniblackfire@gmail.com <mailto:uniblackfire@gmail.com> 可以直接邮件我
